[package]
name = "boardgamer"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17.1", features = ["wgpu"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
plotters = "0.3"
